services:
  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_DB: nestjsdrizzle
      POSTGRES_PASSWORD: 123
    networks:
      - api-nestjs-network

networks:
  api-nestjs-network:
